#!/usr/bin/env python3
"""
Convert a LAZ/LAS file to the raycloud PLY binary layout used by the RCT
pipeline (x,y,z,time double + nx,ny,nz float + rgba uchar, 48 B/record).

Streams in chunks so a 69M-pt hectare fits in bounded memory. Time column:
LAS gpstime (or 0 if point format has none). Normals: 0,0,0. RGB from the
LAS rgb dim (or 255,111,3 default marker).

Usage: laz_to_ply.py in.laz out.ply
"""
from __future__ import annotations
import struct, sys
import laspy

REC = 4 * 8 + 3 * 4 + 4 * 1  # 48
HDR_TMPL = (
    "ply\nformat binary_little_endian 1.0\n"
    "comment generated by raycloudtools library\n"
    "element vertex {n:012d}\n"
    "property double x\nproperty double y\nproperty double z\n"
    "property double time\n"
    "property float nx\nproperty float ny\nproperty float nz\n"
    "property uchar red\nproperty uchar green\nproperty uchar blue\n"
    "property uchar alpha\nend_header\n"
)

def main():
    if len(sys.argv) != 3:
        sys.exit("usage: laz_to_ply.py in.laz out.ply")
    src, dst = sys.argv[1], sys.argv[2]
    with laspy.open(src) as f:
        total = f.header.point_count
        # fixed-width placeholder count keeps offset stable
        with open(dst, "wb") as g:
            g.write(HDR_TMPL.format(n=0).encode())
            n = 0
            for pts in f.chunk_iterator(4_000_000):
                x = pts.x
                y = pts.y
                z = pts.z
                # time: gpstime if present, else 0
                try:
                    t = pts.gps_time
                except Exception:
                    t = x * 0.0  # zeros
                has_rgb = "red" in pts.point_format.dimension_names
                try:
                    r, grr, b = (pts.red, pts.green, pts.blue) if has_rgb else (None,) * 3
                except Exception:
                    r = grr = b = None
                buf = bytearray(len(x) * REC)
                for i in range(len(x)):
                    off = i * REC
                    struct.pack_into("<dddd", buf, off, x[i], y[i], z[i], float(t[i]))
                    struct.pack_into("<fff", buf, off + 32, 0.0, 0.0, 0.0)
                    if r is not None:
                        struct.pack_into(
                            "<BBBB", buf, off + 44,
                            int(r[i] / 257) % 256, int(grr[i] / 257) % 256,
                            int(b[i] / 257) % 256, 255,
                        )
                    else:
                        struct.pack_into("<BBBB", buf, off + 44, 255, 111, 3, 255)
                g.write(buf)
                n += len(x)
                print(f"  {n:,}/{total:,}", end="\r")
            # patch count in place (fixed 12-digit width)
            marker = "element vertex "
            g.seek(HDR_TMPL.index(marker) + len(marker))
            g.write(b"%012d" % n)
    print(f"\nwrote {dst}: {n:,} points")

if __name__ == "__main__":
    main()
