#!/usr/bin/env python3
"""
rct_auto_tiling — step 1: split a too-big raycloud PLY into buffered tiles.

Streaming + vectorized (numpy). Chunk-wise pass reads the binary PLY and
assigns every point to its nominal tile (half-open) AND to the neighbouring
tiles whose buffer ring covers it. Writes per tile:
  tile_<i>_<j>.ply    nominal points + buffer-ring points (boundary-safe data).

The merge step crops each file back to its nominal extent with the SAME
half-open predicate -> watertight, a point is never emitted twice and never
dropped.

Memory is bounded: one chunk held at a time, one writer per tile.
"""
from __future__ import annotations
import argparse, json, math, os, sys, time
import numpy as np
from typing import Dict, List, Tuple

RECORD = 4*8 + 3*4 + 4*1   # x y z time (double) + nx ny nz (float) + r g b a (uchar) = 48
# Fixed-width point count (12 digits) so the header has CONSTANT length
# regardless of n — the final header rewrite at close never shifts the data.
PLY_HEADER_TMPL = (
    "ply\nformat binary_little_endian 1.0\n"
    "comment generated by raycloudtools library\n"
    "element vertex {n:>12d}\n"
    "property double x\nproperty double y\nproperty double z\nproperty double time\n"
    "property float nx\nproperty float ny\nproperty float nz\n"
    "property uchar red\nproperty uchar green\nproperty uchar blue\nproperty uchar alpha\n"
    "end_header\n"
)
HEADER_LEN = len(PLY_HEADER_TMPL.format(n=0))  # constant
DT = np.dtype([
    ("x", "<f8"), ("y", "<f8"), ("z", "<f8"), ("time", "<f8"),
    ("nx", "<f4"), ("ny", "<f4"), ("nz", "<f4"),
    ("red", "u1"), ("green", "u1"), ("blue", "u1"), ("alpha", "u1"),
])


def read_hdr(path: str) -> Tuple[int, int, List[str]]:
    names: List[str] = []
    n_points = 0
    hdr_bytes = 0
    with open(path, "rb") as f:
        while True:
            line = f.readline()
            hdr_bytes += len(line)
            if not line:
                raise ValueError("no end_header")
            t = line.rstrip(b"\r\n")
            if t.startswith(b"element vertex"):
                n_points = int(t.split()[-1])
            elif t.startswith(b"property "):
                names.append(t.decode().split()[-1])
            elif t.startswith(b"end_header"):
                break
    return n_points, hdr_bytes, names


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("--length", type=float, required=True)
    ap.add_argument("--buffer", type=float, default=10.0)
    ap.add_argument("--origin", nargs=2, type=float, default=None, metavar=("X", "Y"))
    ap.add_argument("--outdir", default="tiles")
    ap.add_argument("--prefix", default="tile")
    args = ap.parse_args()

    os.makedirs(args.outdir, exist_ok=True)
    n_total, hdr_bytes, names = read_hdr(args.input)
    if names[:4] != ["x", "y", "z", "time"]:
        sys.exit(f"unexpected PLY layout {names}")

    CHUNK = 32 << 20
    # Pass 1 — bbox
    minx = miny = float("inf"); maxx = maxy = float("-inf")
    count = 0
    t0 = time.time()
    with open(args.input, "rb") as f:
        f.seek(hdr_bytes)
        while True:
            buf = f.read(CHUNK)
            if not buf:
                break
            rem = len(buf) % RECORD
            if rem:
                buf = buf[:-rem]
                f.seek(-rem, 1)
            arr = np.frombuffer(buf, dtype=DT, count=len(buf)//RECORD)
            if arr.size == 0:
                continue
            count += arr.size
            minx = min(minx, arr["x"].min()); maxx = max(maxx, arr["x"].max())
            miny = min(miny, arr["y"].min()); maxy = max(maxy, arr["y"].max())
    t1 = time.time()
    print(f"pass1: {count} pts in {t1-t0:.1f}s, bbox x[{minx:.3f},{maxx:.3f}] y[{miny:.3f},{maxy:.3f}] (hdr {n_total})", flush=True)
    if count != n_total:
        print("WARN: count mismatch vs header", flush=True)
    maxx += 1e-9; maxy += 1e-9

    ox, oy = args.origin if args.origin else (math.floor(minx), math.floor(miny))
    if args.origin is None:
        print(f"origin=({ox},{oy})", flush=True)

    L = args.length; B = args.buffer
    i0 = math.floor((minx - ox) / L); i1 = math.ceil((maxx - ox) / L)
    j0 = math.floor((miny - oy) / L); j1 = math.ceil((maxy - oy) / L)
    keys = [(i, j) for i in range(i0, i1) for j in range(j0, j1)]
    if not keys:
        sys.exit("empty grid")
    kidx = {k: n for n, k in enumerate(keys)}
    print(f"grid {i1-i0}x{j1-j0} = {len(keys)} tiles, length={L}, buffer={B}", flush=True)

    # tile nominal extents
    lo_x = np.array([ox + i*L - B for (i, j) in keys])
    hi_x = np.array([ox + (i+1)*L + B for (i, j) in keys])
    lo_y = np.array([oy + j*L - B for (i, j) in keys])
    hi_y = np.array([oy + (j+1)*L + B for (i, j) in keys])

    writers = [open(os.path.join(args.outdir, f"{args.prefix}_{i}_{j}.ply"), "wb") for (i, j) in keys]
    for w, k in zip(writers, keys):
        w.write(PLY_HEADER_TMPL.format(n=0).encode())
    # owner count files (per tile: how many of ITS OWN nominal points it holds)
    owner_files = [open(os.path.join(args.outdir, f"{args.prefix}_{i}_{j}.owners.json"), "w")
                   for (i, j) in keys]

    # Pass 2 — stream + assign to (nominal + buffered neighbouring tiles)
    counts = np.zeros(len(keys), dtype=np.int64)
    written = np.zeros(len(keys), dtype=np.int64)
    n_written = 0
    t2 = time.time()
    with open(args.input, "rb") as f:
        f.seek(hdr_bytes)
        while True:
            buf = f.read(CHUNK)
            if not buf:
                break
            rem = len(buf) % RECORD
            if rem:
                buf = buf[:-rem]
                f.seek(-rem, 1)
            arr = np.frombuffer(buf, dtype=DT, count=len(buf)//RECORD)
            if arr.size == 0:
                continue
            x = arr["x"]; y = arr["y"]
            ci = np.floor((x - ox) / L).astype(np.int64)
            cj = np.floor((y - oy) / L).astype(np.int64)
            # buffered membership = 3x3 ring of nominal cells, neighbours clipped to grid
            for di in (-1, 0, 1):
                ix = ci + di
                inside_i = (ix >= i0) & (ix < i1)
                if not bool(inside_i.any()):
                    continue
                mx = inside_i & (x >= ox + ix*L - B) & (x < ox + (ix+1)*L + B)
                for dj in (-1, 0, 1):
                    jy = cj + dj
                    m = mx & (jy >= j0) & (jy < j1) \
                        & (y >= oy + jy*L - B) & (y < oy + (jy+1)*L + B)
                    if not m.any():
                        continue
                    fi = (ix - i0) * (j1 - j0) + (jy - j0)
                    for u in np.unique(fi[m]):
                        sel = arr[m & (fi == u)]
                        writers[u].write(sel.tobytes())
                        written[u] += sel.size
                        n_written += sel.size
            # nominal counts
            fi = (ci - i0) * (j1 - j0) + (cj - j0)
            np.add.at(counts, fi, 1)
    t3 = time.time()
    print(f"pass2: streamed in {t3-t2:.1f}s, total buffered writes = {n_written}", flush=True)

    # finalise: write real point counts into headers (points actually in the file
    # = nominal + buffer ring; that is what rayprocess sees)
    for u, w in enumerate(writers):
        w.flush()
        w.seek(0)
        w.write(PLY_HEADER_TMPL.format(n=int(written[u])).encode())
        w.close()
        json.dump({"owner": int(counts[u]), "in_file": int(written[u]),
                   "prefix": args.prefix, "i": keys[u][0], "j": keys[u][1]}, owner_files[u])
        owner_files[u].close()

    nominal_sum = int(counts.sum())
    print(f"nominal sum = {nominal_sum} | input = {n_total} | delta = {nominal_sum - n_total} | buffered total = {n_written}", flush=True)
    if nominal_sum != n_total:
        print("FAIL: nominal sum != input — partition not watertight", flush=True)
        return 2
    print("PASS: nominal tile point sum == input point count (no loss, no dup at point level)", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
