
FROM rocker/r-ver:4.3.1

# Instalace systémových závislostí (nutné pro lidR)
RUN apt-get update && apt-get install -y \
    libgdal-dev \
    libproj-dev \
    libgeos-dev \
    libudunits2-dev \
    libcurl4-openssl-dev \
    libxml2-dev \
    libssl-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Instalace R balíčku lidR
RUN R -e "install.packages('lidR', repos = 'https://cloud.r-project.org')"

# Pracovní složka uvnitř kontejneru
WORKDIR /scripts

# Výchozí příkaz (spouštět Rscript s argumentem - název skriptu)
ENTRYPOINT ["Rscript"]
