
# HARDCODED COL NAMEs 
TAG_NO.COL <- "tag"
IS.NEW.RECORD <- "is.new.record"
IS.ERROR.COL <- "collision"
FID.COL <- "fid"
UUID.COL <- "uuid"
SPECIES.COL <- "species"
SPECIES.OLD.COL <- "species_o"
RM_ID.COL <- "id_point"
STATUS_NEW.COL <- "status"
STATUS_OLD.COL <- "status_old"
DBH_NEW.COL <- "dbh"
DBH_OLD.COL <- "dbh_old"
HEIGHT.COL <- "height"
DECAY.COL <- "decay"
MULTIPLICITY.COL <- "multi_stem"
TREE_ID.COL <- "tree_id"
STEM_ID.COL <- "stem_id"
LOG_ID.COL <- "piece_id"
EDIT_DATE.COL <- "date"
EDIT_BY.COL <- "crew"
ERROR.COL <- "error"
#------------------------------------------------------------------
# LAYER NAMES
STANDING.LAYER.NAME <- "ZH_census_2024_S_posun"
LYING.LAYER.NAME <- "ZH_census_L_2024_posun"
BOUNDARY.LAYER.NAME <- "ZH_boundaries"
#------------------------------------------------------------------
#PATHS TO DATA
PROJECT.PATH <- "src/permanent_layers/ZH_census_2024_geopackage.gpkg"
STANDING.PATH <- "autogenerated/unique_standing.rds"
LYING.PATH <- "autogenerated/unique_lying.rds"
GPKG.NAME <- "ZH_census_2024_geopackage.gpkg"
#------------------------------------------------------------------
# STATUS GROUPS
ALIVE.STATUSES <- c("AI","AB","DAB","AL","ALM","AU","AC")
DEAD.STATUSES <- c("DB","DI","DU","SH","DP","NN","NIC","BLS")